function (wgt, dataValue) {
	var binder = zkbind.$('$myWindow');
	
	Caman("#" + wgt.uuid, wgt.getSrc(), function () {
		this
			.contrast(dataValue.contrast)
			.brightness(dataValue.brightness)
			.colorize(dataValue.color, 20)
			.render(function() {
				// Get the canvas generated by camanjs that replaces the original image
				var canvas = document.getElementById(wgt.uuid);
				// Extract the jpeg data from this canvas
				var jpegData = canvas.toDataURL("image/jpeg");

				// Put the processed image client-side to an other image
				var destinationId = canvas.dataset.jimpSource;
				var allImages = document.getElementsByTagName('img');
				for (var i=0; i<allImages.length; i++) {
					var currentImage = allImages[i];
					if (currentImage.dataset.jimpDestination == destinationId) {
						currentImage.setAttribute('src', jpegData);
					}
				}
				
				// Send the processed image to the view model, only if needed
				if (dataValue.sendToServer) {
					binder.command('camanCalculationFinished', {data: jpegData});
				}
			});
	});
}